timezone: Europe/Paris
lang: fr-FR
google_analytics: 'UA-74142838-2'
title: My noteboat, l'appli des plaisanciers
markdown: kramdown
paginate: 10
show_drafts: false
paginate_path: "/blog/page:num"
excerpt_separator: <!--break-->
url: "http://www.mynoteboat.fr"
plugins:
  - jekyll-sitemap
